# Application settings
app:
  name: MCP-Graph
  version: 0.1.0

# API settings
api:
  port: 8080

# Neo4j settings
neo4j:
  uri: bolt://localhost:7687
  username: "neo4j"
  password: "abcabcabc"

# MCP settings
mcp:
  useSSE: true
  address: :3000

# Shutdown settings
shutdown:
  timeout: 5s
