services:
  # MCP Graph Service
  mcp-graph:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MCPGRAPH_NEO4J_URI=bolt://memgraph:7687
      - MCPGRAPH_NEO4J_USERNAME=
      - MCPGRAPH_NEO4J_PASSWORD=
      - MCPGRAPH_MCP_USESSE=true
      - MCPGRAPH_MCP_ADDRESS=:3000
    depends_on:
      - memgraph
    restart: unless-stopped
    networks:
      - mcp-graph-network

  # Memgraph - Graph Database
  memgraph:
    image: memgraph/memgraph:latest
    ports:
      - "7687:7687"  # Bolt protocol
      - "7444:7444"  # HTTP API
      - "3000:3000"  # Memgraph Lab UI
    volumes:
      - memgraph-data:/var/lib/memgraph
    environment:
      - MEMGRAPH_STORAGE_MODE=PERSISTENT
    restart: unless-stopped
    networks:
      - mcp-graph-network

volumes:
  memgraph-data:

networks:
  mcp-graph-network:
    driver: bridge
